config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "meals#index"
  resources :meals do
    resources :ingredients, only: [:new, :create]
  end
  # post '/ingredients', to: 'meals#create_new_ingredients', as: :ingredients
  resources :lists, only: [:new, :edit, :create, :show, :update]

  post "/lists/:list_id/meals/:id", to: 'list_meals#create'
  # I created this custom route in order to have access to the list and meal ids from the list_meals#create method so that I can properly create list_meal objects to save to the database that accurately match up the proper lists and meals. 

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

end

app/models/user.rb
class User < ApplicationRecord
  has_many :meals
  # has_many :meal_items, through: :meals
  has_many :lists

  validates_uniqueness_of :email
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    if @user = helpers.current_user
      @lists = @user.lists
    else
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h2 class="center">Sign Up!</h2>

<%= render '/errors' %>

<div class="sign-up">
  <%= form_for @user do |f| %>
    <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    </p>

    <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </p>

    <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </p>

    <p>
    <%= f.submit "Sign Up" %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>My Lists</h2>

<% @lists.each do |list| %>
  <div>
    <%= link_to list.name, list_path(list) %>
  </div>
<% end %>