config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "meals#index"
  resources :meals do
    resources :ingredients, only: [:new, :create]
  end
  # post '/ingredients', to: 'meals#create_new_ingredients', as: :ingredients
  resources :lists, only: [:new, :edit, :create, :show, :update]

  post "/lists/:list_id/meals/:id", to: 'list_meals#create'
  # I created this custom route in order to have access to the list and meal ids from the list_meals#create method so that I can properly create list_meal objects to save to the database that accurately match up the proper lists and meals. 

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :meal_items
  has_many :meals, through: :meal_items
  # validates_presence_of :name, :unit_type
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @meal = Meal.find_by(id: params[:meal_id])
    @ingredient = Ingredient.new
    @meal_item = MealItem.new
  end

  def create
    @meal = Meal.find_by(id: params[:meal_id])
    @new_ingredient = Ingredient.new(ingredient_params)

    if @new_ingredient.save
      @new_meal_item = @new_ingredient.meal_items.new(meal_item_params)
      if @new_meal_item.save
        respond_to do |format|
          @ingredient = Ingredient.new
          @meal_item = MealItem.new
          format.html { render 'new' }
          format.js {}
        end
      else
        @errors = @meal_item.errors.full_messages
        @new_ingredient.destroy
        render 'new'
      end
    else
      @errors = @ingredient.errors.full_messages
      render 'new'
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :unit_type)
  end

  def meal_item_params
    params.require(:meal_item).permit(:meal_id, :quantity, :instruction)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient.html.erb
<ul>
  <li><%= @new_ingredient.name %></li>
  <ul>
    <li>
      <%= "#{@new_meal_item.quantity}, #{@new_ingredient.unit_type}" %>
    </li>
  </ul>
</ul>

app/views/ingredients/_ingredient_form.html.erb
<div id="ingredient-form">
  <%= render '/errors' %>
  <%= form_tag meal_ingredients_path, remote: true do %>
    <%= fields_for @ingredient do |ingredient_f| %>
      <p>
        <%= ingredient_f.label :Ingredient_name %>
        <%= ingredient_f.text_field :name %>
      </p>
      <p>
        <%= ingredient_f.label :unit_type %>
        <%= ingredient_f.text_field :unit_type %>
      </p>
    <% end %>


    <%= fields_for @meal_item do |meal_item_f| %>
      <%= meal_item_f.hidden_field :meal_id, value: @meal.id %>
      <p>
        <%= meal_item_f.label :quantity %>
        <%= meal_item_f.text_field :quantity %>
      </p>
      <p>
        <%= meal_item_f.label :instruction %>
        <%= meal_item_f.text_field :instruction %>
      </p>
    <% end %>

  <p>
    <%= submit_tag "Submit" %>
  </p>
  <% end %>
</div>

app/views/ingredients/_ingredients.html.erb
<ul>
  <% @meal.ingredients_array.each do |ingredient| %>
    <li><%= ingredient[:name] %></li>
    <ul>
      <li>
        <%= "#{ingredient[:quantity]} #{ingredient[:unit]}" %>
      </li>
    </ul>
  <% end %>
</ul>

app/views/ingredients/create.js.erb
$("#ingredient-form").remove()
$(".ingredients").append(" <%= j render 'ingredient' %>")
$(".form").after(" <%= j render 'ingredient_form' %> ")

app/views/ingredients/new.html.erb
<h3 class="center"><%= @meal.name.capitalize %></h3>

<div class="ingredients center">
  <% if @meal.ingredients.length > 0 %>
    <%= render 'ingredients' %>
  <% end %>
</div>
<hr>

<div class="form">
  <%= render 'ingredient_form' %>
</div>