config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "meals#index"
  resources :meals do
    resources :ingredients, only: [:new, :create]
  end
  # post '/ingredients', to: 'meals#create_new_ingredients', as: :ingredients
  resources :lists, only: [:new, :edit, :create, :show, :update]

  post "/lists/:list_id/meals/:id", to: 'list_meals#create'
  # I created this custom route in order to have access to the list and meal ids from the list_meals#create method so that I can properly create list_meal objects to save to the database that accurately match up the proper lists and meals. 

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :meal_items
  has_many :ingredients, through: :meal_items
  # accepts_nested_attributes_for :meal_items
  validates_presence_of :name

  def ingredients_array
    arr = []
    self.meal_items.each do |item|
      arr << { name: item.ingredient.name, unit: item.ingredient.unit_type, quantity: item.quantity }
    end
    return arr
  end

end
 

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.includes(:meal_items).includes(:ingredients)
    
  end

  def new
    if !helpers.logged_in?
      redirect_to root_path
    end
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to new_meal_ingredient_path(@meal)
    else
      @errors = @meal.errors.full_messages
      render 'new'
    end
  end

  def show
    @meal = Meal.find_by(id: params[:id])
  end


  private

  def meal_params
    params.require(:meal).permit(:user_id, :name)
  end

  def ingredient_params(ingred_params)
    ingred_params.permit(:name, :unit_type)
  end

  def meal_item_params(meal_item_params)
    meal_item_params.permit(:quantity, :instruction, :meal_id)
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_ingredient_form.html.erb
<h3 class="center"><%= @meal.name.capitalize %></h3>
<div id="ingredient-form">
  <%= form_tag ingredients_path do %>
    <% @ingredients.each do |array| %>
      <%= fields_for 'ingredients[]', array[0] do |ingredient_f| %>
        <p>
          <%= ingredient_f.label :Ingredient_name %>
          <%= ingredient_f.text_field :name %>
        </p>
        <p>
          <%= ingredient_f.label :unit_type %>
          <%= ingredient_f.text_field :unit_type %>
        </p>
      <% end %>


    <%= fields_for 'meal_items[]', array[1] do |meal_item_f| %>
      <%= meal_item_f.hidden_field :meal_id, value: @meal.id %>
      <p>
        <%= meal_item_f.label :quantity %>
        <%= meal_item_f.text_field :quantity %>
      </p>
      <p>
        <%= meal_item_f.label :instruction %>
        <%= meal_item_f.text_field :instruction %>
      </p>
    <% end %>
  <% end %>

  <p>
    <%= submit_tag "Submit" %>
  </p>
</div>
<% end %>

app/views/meals/create.js.erb
<% if @errors %>
  $("div.errors").remove()
  $("h2").after(" <%= j (render '/errors') %> ")
<% else %>
  $("#meal-form").remove()
  $("h2").after(" <%= j (render 'ingredient_form') %>")
  $("h2").remove()
<% end %>

app/views/meals/index.html.erb
<div>
  <h2 class="center">Meals</h2>

  <% if logged_in? %>
    <div class="center">
      <%= link_to "Create New Meal", new_meal_path, class: "waves-effect waves-light btn" %>
      <%= link_to "Create New List", new_list_path, class: "waves-effect waves-light btn" %>
    </div>
  <% end %>
  

  <div class="row">
    <% @meals.each do |meal| %>
      <div class="col s12 m6 l4">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= meal.name %></span>
              <ul>
                <% meal.ingredients_array.each do |ingredient| %>
                  <li><%= ingredient[:name] %></li>
                  <ul>
                    <li>
                      <%= "#{ingredient[:quantity]} #{ingredient[:unit]}" %>
                    </li>
                  </ul>
                <% end %>
              </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  
</div>

app/views/meals/new.html.erb
<div>
  <h2 class="center">New Meal</h2>

  <div class="center errors">
    <%= render '/errors' %>
  </div>

  <div id="meal-form">
    <%= form_for @meal do |f| %>
      <p>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </p>
      <p>
        <%= f.label :Meal_name %>
        <%= f.text_field :name %>
      </p>
        <%= f.label "Click 'Next' to add ingredients" %>
        <%= f.submit "Next" %>
    <% end %>
  </div>
</div>

app/views/meals/new_ingredient.js.erb
$("div.ingredients").append(" <%= j (render 'ingredient_form') %>")

app/views/meals/show.html.erb
<h2><%= @meal.name.capitalize %></h2>

<% @meal.ingredients_array.each do |ingredient| %>
  <ul>
    <li><%= ingredient[:name] %></li>
    <ul>
      <li>
        <%= "#{ingredient[:quantity]} #{ingredient[:unit]}" %>
      </li>
    </ul>
  </ul>
<% end %>